### ISSUE TITLE
iPhone X 上 BoxJs 样式兼容性调整

### ISSUE THREAD

**Issue by chouchoui** [chavyleung/scripts#169]
需要追加以下样式
```css
.v-bottom-navigation,
.v-bottom-sheet {
    padding-bottom: constant(safe-area-inset-bottom);
    padding-bottom: env(safe-area-inset-bottom);
}

.v-bottom-navigation{
    box-sizing: content-box;
}

.v-bottom-navigation button {
    box-sizing: border-box;
}

.v-main__wrap {
    padding-bottom: 56px;
    padding-bottom: calc(56px + constant(safe-area-inset-bottom));
    padding-bottom: calc(56px + env(safe-area-inset-bottom));
}

.v-speed-dial {
    bottom: calc(72px + constant(safe-area-inset-bottom));
    bottom: calc(72px + env(safe-area-inset-bottom));
}
```

效果如图
![IMG_5BA5F09203D1-1](https://user-images.githubusercontent.com/14866249/87859772-33bd9400-c96a-11ea-850a-fe10d460a8e8.jpeg)
